/**
 * AWS Icon Categories - Auto-generated
 *
 * This file is auto-generated from official AWS icons.
 * To regenerate, run: npm run process-cloud-icons
 *
 * Total icons: 306
 */

import type { IconCategory } from '../types';

const awsCategoriesArray: IconCategory[] = [
  {
    label: 'All Services',
    source: 'aws',
    icons: [
      {
        id: 'aws-clean-rooms',
        label: 'Clean Rooms',
        color: '#FF9900',
        source: 'aws',
        tags: ["clean","rooms"],
      },
      {
        id: 'aws-data-exchange',
        label: 'Data Exchange',
        color: '#FF9900',
        source: 'aws',
        tags: ["data","exchange"],
      },
      {
        id: 'aws-entity-resolution',
        label: 'Entity Resolution',
        color: '#FF9900',
        source: 'aws',
        tags: ["entity","resolution"],
      },
      {
        id: 'aws-glue-databrew',
        label: 'Glue DataBrew',
        color: '#FF9900',
        source: 'aws',
        tags: ["glue","databrew"],
      },
      {
        id: 'aws-glue',
        label: 'Glue',
        color: '#FF9900',
        source: 'aws',
        tags: ["glue"],
      },
      {
        id: 'aws-lake-formation',
        label: 'Lake Formation',
        color: '#FF9900',
        source: 'aws',
        tags: ["lake","formation"],
      },
      {
        id: 'aws-athena',
        label: 'Athena',
        color: '#FF9900',
        source: 'aws',
        tags: ["athena"],
      },
      {
        id: 'aws-cloudsearch',
        label: 'CloudSearch',
        color: '#FF9900',
        source: 'aws',
        tags: ["cloudsearch"],
      },
      {
        id: 'aws-data-firehose',
        label: 'Data Firehose',
        color: '#FF9900',
        source: 'aws',
        tags: ["data","firehose"],
      },
      {
        id: 'aws-datazone',
        label: 'DataZone',
        color: '#FF9900',
        source: 'aws',
        tags: ["datazone"],
      },
      {
        id: 'aws-emr',
        label: 'EMR',
        color: '#FF9900',
        source: 'aws',
        tags: ["emr"],
      },
      {
        id: 'aws-finspace',
        label: 'FinSpace',
        color: '#FF9900',
        source: 'aws',
        tags: ["finspace"],
      },
      {
        id: 'aws-kinesis-data-streams',
        label: 'Kinesis Data Streams',
        color: '#FF9900',
        source: 'aws',
        tags: ["kinesis","data","streams"],
      },
      {
        id: 'aws-kinesis-video-streams',
        label: 'Kinesis Video Streams',
        color: '#FF9900',
        source: 'aws',
        tags: ["kinesis","video","streams"],
      },
      {
        id: 'aws-kinesis',
        label: 'Kinesis',
        color: '#FF9900',
        source: 'aws',
        tags: ["kinesis"],
      },
      {
        id: 'aws-managed-service-for-apache-flink',
        label: 'Managed Service for Apache Flink',
        color: '#FF9900',
        source: 'aws',
        tags: ["managed","service","for","apache","flink"],
      },
      {
        id: 'aws-managed-streaming-for-apache-kafka',
        label: 'Managed Streaming for Apache Kafka',
        color: '#FF9900',
        source: 'aws',
        tags: ["managed","streaming","for","apache","kafka"],
      },
      {
        id: 'aws-opensearch-service',
        label: 'OpenSearch Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["opensearch","service"],
      },
      {
        id: 'aws-quicksight',
        label: 'QuickSight',
        color: '#FF9900',
        source: 'aws',
        tags: ["quicksight"],
      },
      {
        id: 'aws-redshift',
        label: 'Redshift',
        color: '#FF9900',
        source: 'aws',
        tags: ["redshift"],
      },
      {
        id: 'aws-sagemaker',
        label: 'SageMaker',
        color: '#FF9900',
        source: 'aws',
        tags: ["sagemaker"],
      },
      {
        id: 'aws-appsync',
        label: 'AppSync',
        color: '#FF9900',
        source: 'aws',
        tags: ["appsync"],
      },
      {
        id: 'aws-b2b-data-interchange',
        label: 'B2B Data Interchange',
        color: '#FF9900',
        source: 'aws',
        tags: ["b2b","data","interchange"],
      },
      {
        id: 'aws-express-workflows',
        label: 'Express Workflows',
        color: '#FF9900',
        source: 'aws',
        tags: ["express","workflows"],
      },
      {
        id: 'aws-step-functions',
        label: 'Step Functions',
        color: '#FF9900',
        source: 'aws',
        tags: ["step","functions"],
      },
      {
        id: 'aws-appflow',
        label: 'AppFlow',
        color: '#FF9900',
        source: 'aws',
        tags: ["appflow"],
      },
      {
        id: 'aws-eventbridge',
        label: 'EventBridge',
        color: '#FF9900',
        source: 'aws',
        tags: ["eventbridge"],
      },
      {
        id: 'aws-mq',
        label: 'MQ',
        color: '#FF9900',
        source: 'aws',
        tags: ["mq"],
      },
      {
        id: 'aws-managed-workflows-for-apache-airflow',
        label: 'Managed Workflows for Apache Airflow',
        color: '#FF9900',
        source: 'aws',
        tags: ["managed","workflows","for","apache","airflow"],
      },
      {
        id: 'aws-simple-notification-service',
        label: 'Simple Notification Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["simple","notification","service"],
      },
      {
        id: 'aws-simple-queue-service',
        label: 'Simple Queue Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["simple","queue","service"],
      },
      {
        id: 'aws-app-studio',
        label: 'App Studio',
        color: '#FF9900',
        source: 'aws',
        tags: ["app","studio"],
      },
      {
        id: 'aws-deep-learning-amis',
        label: 'Deep Learning AMIs',
        color: '#FF9900',
        source: 'aws',
        tags: ["deep","learning","amis"],
      },
      {
        id: 'aws-deep-learning-containers',
        label: 'Deep Learning Containers',
        color: '#FF9900',
        source: 'aws',
        tags: ["deep","learning","containers"],
      },
      {
        id: 'aws-deepcomposer',
        label: 'DeepComposer',
        color: '#FF9900',
        source: 'aws',
        tags: ["deepcomposer"],
      },
      {
        id: 'aws-deepracer',
        label: 'DeepRacer',
        color: '#FF9900',
        source: 'aws',
        tags: ["deepracer"],
      },
      {
        id: 'aws-healthimaging',
        label: 'HealthImaging',
        color: '#FF9900',
        source: 'aws',
        tags: ["healthimaging"],
      },
      {
        id: 'aws-healthlake',
        label: 'HealthLake',
        color: '#FF9900',
        source: 'aws',
        tags: ["healthlake"],
      },
      {
        id: 'aws-healthomics',
        label: 'HealthOmics',
        color: '#FF9900',
        source: 'aws',
        tags: ["healthomics"],
      },
      {
        id: 'aws-healthscribe',
        label: 'HealthScribe',
        color: '#FF9900',
        source: 'aws',
        tags: ["healthscribe"],
      },
      {
        id: 'aws-neuron',
        label: 'Neuron',
        color: '#FF9900',
        source: 'aws',
        tags: ["neuron"],
      },
      {
        id: 'aws-panorama',
        label: 'Panorama',
        color: '#FF9900',
        source: 'aws',
        tags: ["panorama"],
      },
      {
        id: 'aws-augmented-ai-a2i',
        label: 'Augmented AI A2I',
        color: '#FF9900',
        source: 'aws',
        tags: ["augmented","ai","a2i"],
      },
      {
        id: 'aws-bedrock',
        label: 'Bedrock',
        color: '#FF9900',
        source: 'aws',
        tags: ["bedrock"],
      },
      {
        id: 'aws-codeguru',
        label: 'CodeGuru',
        color: '#FF9900',
        source: 'aws',
        tags: ["codeguru"],
      },
      {
        id: 'aws-codewhisperer',
        label: 'CodeWhisperer',
        color: '#FF9900',
        source: 'aws',
        tags: ["codewhisperer"],
      },
      {
        id: 'aws-comprehend-medical',
        label: 'Comprehend Medical',
        color: '#FF9900',
        source: 'aws',
        tags: ["comprehend","medical"],
      },
      {
        id: 'aws-comprehend',
        label: 'Comprehend',
        color: '#FF9900',
        source: 'aws',
        tags: ["comprehend"],
      },
      {
        id: 'aws-devops-guru',
        label: 'DevOps Guru',
        color: '#FF9900',
        source: 'aws',
        tags: ["devops","guru"],
      },
      {
        id: 'aws-elastic-inference',
        label: 'Elastic Inference',
        color: '#FF9900',
        source: 'aws',
        tags: ["elastic","inference"],
      },
      {
        id: 'aws-forecast',
        label: 'Forecast',
        color: '#FF9900',
        source: 'aws',
        tags: ["forecast"],
      },
      {
        id: 'aws-fraud-detector',
        label: 'Fraud Detector',
        color: '#FF9900',
        source: 'aws',
        tags: ["fraud","detector"],
      },
      {
        id: 'aws-kendra',
        label: 'Kendra',
        color: '#FF9900',
        source: 'aws',
        tags: ["kendra"],
      },
      {
        id: 'aws-lex',
        label: 'Lex',
        color: '#FF9900',
        source: 'aws',
        tags: ["lex"],
      },
      {
        id: 'aws-lookout-for-equipment',
        label: 'Lookout for Equipment',
        color: '#FF9900',
        source: 'aws',
        tags: ["lookout","for","equipment"],
      },
      {
        id: 'aws-lookout-for-metrics',
        label: 'Lookout for Metrics',
        color: '#FF9900',
        source: 'aws',
        tags: ["lookout","for","metrics"],
      },
      {
        id: 'aws-lookout-for-vision',
        label: 'Lookout for Vision',
        color: '#FF9900',
        source: 'aws',
        tags: ["lookout","for","vision"],
      },
      {
        id: 'aws-monitron',
        label: 'Monitron',
        color: '#FF9900',
        source: 'aws',
        tags: ["monitron"],
      },
      {
        id: 'aws-nova',
        label: 'Nova',
        color: '#FF9900',
        source: 'aws',
        tags: ["nova"],
      },
      {
        id: 'aws-personalize',
        label: 'Personalize',
        color: '#FF9900',
        source: 'aws',
        tags: ["personalize"],
      },
      {
        id: 'aws-polly',
        label: 'Polly',
        color: '#FF9900',
        source: 'aws',
        tags: ["polly"],
      },
      {
        id: 'aws-q',
        label: 'Q',
        color: '#FF9900',
        source: 'aws',
        tags: ["q"],
      },
      {
        id: 'aws-rekognition',
        label: 'Rekognition',
        color: '#FF9900',
        source: 'aws',
        tags: ["rekognition"],
      },
      {
        id: 'aws-sagemaker-ai',
        label: 'SageMaker AI',
        color: '#FF9900',
        source: 'aws',
        tags: ["sagemaker","ai"],
      },
      {
        id: 'aws-sagemaker-ground-truth',
        label: 'SageMaker Ground Truth',
        color: '#FF9900',
        source: 'aws',
        tags: ["sagemaker","ground","truth"],
      },
      {
        id: 'aws-sagemaker-studio-lab',
        label: 'SageMaker Studio Lab',
        color: '#FF9900',
        source: 'aws',
        tags: ["sagemaker","studio","lab"],
      },
      {
        id: 'aws-textract',
        label: 'Textract',
        color: '#FF9900',
        source: 'aws',
        tags: ["textract"],
      },
      {
        id: 'aws-transcribe',
        label: 'Transcribe',
        color: '#FF9900',
        source: 'aws',
        tags: ["transcribe"],
      },
      {
        id: 'aws-translate',
        label: 'Translate',
        color: '#FF9900',
        source: 'aws',
        tags: ["translate"],
      },
      {
        id: 'aws-apache-mxnet-on-aws',
        label: 'Apache MXNet on AWS',
        color: '#FF9900',
        source: 'aws',
        tags: ["apache","mxnet","on","aws"],
      },
      {
        id: 'aws-pytorch-on-aws',
        label: 'PyTorch on AWS',
        color: '#FF9900',
        source: 'aws',
        tags: ["pytorch","on","aws"],
      },
      {
        id: 'aws-tensorflow-on-aws',
        label: 'TensorFlow on AWS',
        color: '#FF9900',
        source: 'aws',
        tags: ["tensorflow","on","aws"],
      },
      {
        id: 'aws-managed-blockchain',
        label: 'Managed Blockchain',
        color: '#FF9900',
        source: 'aws',
        tags: ["managed","blockchain"],
      },
      {
        id: 'aws-quantum-ledger-database',
        label: 'Quantum Ledger Database',
        color: '#FF9900',
        source: 'aws',
        tags: ["quantum","ledger","database"],
      },
      {
        id: 'aws-appfabric',
        label: 'AppFabric',
        color: '#FF9900',
        source: 'aws',
        tags: ["appfabric"],
      },
      {
        id: 'aws-end-user-messaging',
        label: 'End User Messaging',
        color: '#FF9900',
        source: 'aws',
        tags: ["end","user","messaging"],
      },
      {
        id: 'aws-supply-chain',
        label: 'Supply Chain',
        color: '#FF9900',
        source: 'aws',
        tags: ["supply","chain"],
      },
      {
        id: 'aws-wickr',
        label: 'Wickr',
        color: '#FF9900',
        source: 'aws',
        tags: ["wickr"],
      },
      {
        id: 'aws-alexa-for-business',
        label: 'Alexa For Business',
        color: '#FF9900',
        source: 'aws',
        tags: ["alexa","for","business"],
      },
      {
        id: 'aws-chime-sdk',
        label: 'Chime SDK',
        color: '#FF9900',
        source: 'aws',
        tags: ["chime","sdk"],
      },
      {
        id: 'aws-chime',
        label: 'Chime',
        color: '#FF9900',
        source: 'aws',
        tags: ["chime"],
      },
      {
        id: 'aws-connect',
        label: 'Connect',
        color: '#FF9900',
        source: 'aws',
        tags: ["connect"],
      },
      {
        id: 'aws-pinpoint-apis',
        label: 'Pinpoint APIs',
        color: '#FF9900',
        source: 'aws',
        tags: ["pinpoint","apis"],
      },
      {
        id: 'aws-pinpoint',
        label: 'Pinpoint',
        color: '#FF9900',
        source: 'aws',
        tags: ["pinpoint"],
      },
      {
        id: 'aws-simple-email-service',
        label: 'Simple Email Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["simple","email","service"],
      },
      {
        id: 'aws-workdocs-sdk',
        label: 'WorkDocs SDK',
        color: '#FF9900',
        source: 'aws',
        tags: ["workdocs","sdk"],
      },
      {
        id: 'aws-workdocs',
        label: 'WorkDocs',
        color: '#FF9900',
        source: 'aws',
        tags: ["workdocs"],
      },
      {
        id: 'aws-workmail',
        label: 'WorkMail',
        color: '#FF9900',
        source: 'aws',
        tags: ["workmail"],
      },
      {
        id: 'aws-billing-conductor',
        label: 'Billing Conductor',
        color: '#FF9900',
        source: 'aws',
        tags: ["billing","conductor"],
      },
      {
        id: 'aws-budgets',
        label: 'Budgets',
        color: '#FF9900',
        source: 'aws',
        tags: ["budgets"],
      },
      {
        id: 'aws-cost-explorer',
        label: 'Cost Explorer',
        color: '#FF9900',
        source: 'aws',
        tags: ["cost","explorer"],
      },
      {
        id: 'aws-cost-and-usage-report',
        label: 'Cost and Usage Report',
        color: '#FF9900',
        source: 'aws',
        tags: ["cost","and","usage","report"],
      },
      {
        id: 'aws-reserved-instance-reporting',
        label: 'Reserved Instance Reporting',
        color: '#FF9900',
        source: 'aws',
        tags: ["reserved","instance","reporting"],
      },
      {
        id: 'aws-savings-plans',
        label: 'Savings Plans',
        color: '#FF9900',
        source: 'aws',
        tags: ["savings","plans"],
      },
      {
        id: 'aws-app-runner',
        label: 'App Runner',
        color: '#FF9900',
        source: 'aws',
        tags: ["app","runner"],
      },
      {
        id: 'aws-batch',
        label: 'Batch',
        color: '#FF9900',
        source: 'aws',
        tags: ["batch"],
      },
      {
        id: 'aws-compute-optimizer',
        label: 'Compute Optimizer',
        color: '#FF9900',
        source: 'aws',
        tags: ["compute","optimizer"],
      },
      {
        id: 'aws-elastic-beanstalk',
        label: 'Elastic Beanstalk',
        color: '#FF9900',
        source: 'aws',
        tags: ["elastic","beanstalk"],
      },
      {
        id: 'aws-lambda',
        label: 'Lambda',
        color: '#FF9900',
        source: 'aws',
        tags: ["lambda"],
      },
      {
        id: 'aws-local-zones',
        label: 'Local Zones',
        color: '#FF9900',
        source: 'aws',
        tags: ["local","zones"],
      },
      {
        id: 'aws-nitro-enclaves',
        label: 'Nitro Enclaves',
        color: '#FF9900',
        source: 'aws',
        tags: ["nitro","enclaves"],
      },
      {
        id: 'aws-outposts-family',
        label: 'Outposts family',
        color: '#FF9900',
        source: 'aws',
        tags: ["outposts","family"],
      },
      {
        id: 'aws-outposts-rack',
        label: 'Outposts rack',
        color: '#FF9900',
        source: 'aws',
        tags: ["outposts","rack"],
      },
      {
        id: 'aws-outposts-servers',
        label: 'Outposts servers',
        color: '#FF9900',
        source: 'aws',
        tags: ["outposts","servers"],
      },
      {
        id: 'aws-parallel-cluster',
        label: 'Parallel Cluster',
        color: '#FF9900',
        source: 'aws',
        tags: ["parallel","cluster"],
      },
      {
        id: 'aws-parallel-computing-service',
        label: 'Parallel Computing Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["parallel","computing","service"],
      },
      {
        id: 'aws-serverless-application-repository',
        label: 'Serverless Application Repository',
        color: '#FF9900',
        source: 'aws',
        tags: ["serverless","application","repository"],
      },
      {
        id: 'aws-simspace-weaver',
        label: 'SimSpace Weaver',
        color: '#FF9900',
        source: 'aws',
        tags: ["simspace","weaver"],
      },
      {
        id: 'aws-wavelength',
        label: 'Wavelength',
        color: '#FF9900',
        source: 'aws',
        tags: ["wavelength"],
      },
      {
        id: 'aws-dcv',
        label: 'DCV',
        color: '#FF9900',
        source: 'aws',
        tags: ["dcv"],
      },
      {
        id: 'aws-ec2-auto-scaling',
        label: 'EC2 Auto Scaling',
        color: '#FF9900',
        source: 'aws',
        tags: ["ec2","auto","scaling"],
      },
      {
        id: 'aws-ec2-image-builder',
        label: 'EC2 Image Builder',
        color: '#FF9900',
        source: 'aws',
        tags: ["ec2","image","builder"],
      },
      {
        id: 'aws-ec2',
        label: 'EC2',
        color: '#FF9900',
        source: 'aws',
        tags: ["ec2"],
      },
      {
        id: 'aws-elastic-vmware-service',
        label: 'Elastic VMware Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["elastic","vmware","service"],
      },
      {
        id: 'aws-lightsail-for-research',
        label: 'Lightsail for Research',
        color: '#FF9900',
        source: 'aws',
        tags: ["lightsail","for","research"],
      },
      {
        id: 'aws-lightsail',
        label: 'Lightsail',
        color: '#FF9900',
        source: 'aws',
        tags: ["lightsail"],
      },
      {
        id: 'aws-bottlerocket',
        label: 'Bottlerocket',
        color: '#FF9900',
        source: 'aws',
        tags: ["bottlerocket"],
      },
      {
        id: 'aws-elastic-fabric-adapter',
        label: 'Elastic Fabric Adapter',
        color: '#FF9900',
        source: 'aws',
        tags: ["elastic","fabric","adapter"],
      },
      {
        id: 'aws-nice-enginframe',
        label: 'NICE EnginFrame',
        color: '#FF9900',
        source: 'aws',
        tags: ["nice","enginframe"],
      },
      {
        id: 'aws-fargate',
        label: 'Fargate',
        color: '#FF9900',
        source: 'aws',
        tags: ["fargate"],
      },
      {
        id: 'aws-ecs-anywhere',
        label: 'ECS Anywhere',
        color: '#FF9900',
        source: 'aws',
        tags: ["ecs","anywhere"],
      },
      {
        id: 'aws-eks-anywhere',
        label: 'EKS Anywhere',
        color: '#FF9900',
        source: 'aws',
        tags: ["eks","anywhere"],
      },
      {
        id: 'aws-eks-cloud',
        label: 'EKS Cloud',
        color: '#FF9900',
        source: 'aws',
        tags: ["eks","cloud"],
      },
      {
        id: 'aws-eks-distro',
        label: 'EKS Distro',
        color: '#FF9900',
        source: 'aws',
        tags: ["eks","distro"],
      },
      {
        id: 'aws-elastic-container-registry',
        label: 'Elastic Container Registry',
        color: '#FF9900',
        source: 'aws',
        tags: ["elastic","container","registry"],
      },
      {
        id: 'aws-elastic-container-service',
        label: 'Elastic Container Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["elastic","container","service"],
      },
      {
        id: 'aws-elastic-kubernetes-service',
        label: 'Elastic Kubernetes Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["elastic","kubernetes","service"],
      },
      {
        id: 'aws-red-hat-openshift-service-on-aws',
        label: 'Red Hat OpenShift Service on AWS',
        color: '#FF9900',
        source: 'aws',
        tags: ["red","hat","openshift","service","on","aws"],
      },
      {
        id: 'aws-activate',
        label: 'Activate',
        color: '#FF9900',
        source: 'aws',
        tags: ["activate"],
      },
      {
        id: 'aws-iq',
        label: 'IQ',
        color: '#FF9900',
        source: 'aws',
        tags: ["iq"],
      },
      {
        id: 'aws-managed-services',
        label: 'Managed Services',
        color: '#FF9900',
        source: 'aws',
        tags: ["managed","services"],
      },
      {
        id: 'aws-professional-services',
        label: 'Professional Services',
        color: '#FF9900',
        source: 'aws',
        tags: ["professional","services"],
      },
      {
        id: 'aws-support',
        label: 'Support',
        color: '#FF9900',
        source: 'aws',
        tags: ["support"],
      },
      {
        id: 'aws-training-certification',
        label: 'Training Certification',
        color: '#FF9900',
        source: 'aws',
        tags: ["training","certification"],
      },
      {
        id: 'aws-repost-private',
        label: 'rePost Private',
        color: '#FF9900',
        source: 'aws',
        tags: ["repost","private"],
      },
      {
        id: 'aws-repost',
        label: 'rePost',
        color: '#FF9900',
        source: 'aws',
        tags: ["repost"],
      },
      {
        id: 'aws-database-migration-service',
        label: 'Database Migration Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["database","migration","service"],
      },
      {
        id: 'aws-aurora',
        label: 'Aurora',
        color: '#FF9900',
        source: 'aws',
        tags: ["aurora"],
      },
      {
        id: 'aws-documentdb',
        label: 'DocumentDB',
        color: '#FF9900',
        source: 'aws',
        tags: ["documentdb"],
      },
      {
        id: 'aws-dynamodb',
        label: 'DynamoDB',
        color: '#FF9900',
        source: 'aws',
        tags: ["dynamodb"],
      },
      {
        id: 'aws-elasticache',
        label: 'ElastiCache',
        color: '#FF9900',
        source: 'aws',
        tags: ["elasticache"],
      },
      {
        id: 'aws-keyspaces',
        label: 'Keyspaces',
        color: '#FF9900',
        source: 'aws',
        tags: ["keyspaces"],
      },
      {
        id: 'aws-memorydb',
        label: 'MemoryDB',
        color: '#FF9900',
        source: 'aws',
        tags: ["memorydb"],
      },
      {
        id: 'aws-neptune',
        label: 'Neptune',
        color: '#FF9900',
        source: 'aws',
        tags: ["neptune"],
      },
      {
        id: 'aws-rds',
        label: 'RDS',
        color: '#FF9900',
        source: 'aws',
        tags: ["rds"],
      },
      {
        id: 'aws-timestream',
        label: 'Timestream',
        color: '#FF9900',
        source: 'aws',
        tags: ["timestream"],
      },
      {
        id: 'aws-oracle-database-at-aws',
        label: 'Oracle Database at AWS',
        color: '#FF9900',
        source: 'aws',
        tags: ["oracle","database","at","aws"],
      },
      {
        id: 'aws-cloud-control-api',
        label: 'Cloud Control API',
        color: '#FF9900',
        source: 'aws',
        tags: ["cloud","control","api"],
      },
      {
        id: 'aws-cloud-development-kit',
        label: 'Cloud Development Kit',
        color: '#FF9900',
        source: 'aws',
        tags: ["cloud","development","kit"],
      },
      {
        id: 'aws-cloud9',
        label: 'Cloud9',
        color: '#FF9900',
        source: 'aws',
        tags: ["cloud9"],
      },
      {
        id: 'aws-cloudshell',
        label: 'CloudShell',
        color: '#FF9900',
        source: 'aws',
        tags: ["cloudshell"],
      },
      {
        id: 'aws-codeartifact',
        label: 'CodeArtifact',
        color: '#FF9900',
        source: 'aws',
        tags: ["codeartifact"],
      },
      {
        id: 'aws-codebuild',
        label: 'CodeBuild',
        color: '#FF9900',
        source: 'aws',
        tags: ["codebuild"],
      },
      {
        id: 'aws-codecommit',
        label: 'CodeCommit',
        color: '#FF9900',
        source: 'aws',
        tags: ["codecommit"],
      },
      {
        id: 'aws-codedeploy',
        label: 'CodeDeploy',
        color: '#FF9900',
        source: 'aws',
        tags: ["codedeploy"],
      },
      {
        id: 'aws-codepipeline',
        label: 'CodePipeline',
        color: '#FF9900',
        source: 'aws',
        tags: ["codepipeline"],
      },
      {
        id: 'aws-command-line-interface',
        label: 'Command Line Interface',
        color: '#FF9900',
        source: 'aws',
        tags: ["command","line","interface"],
      },
      {
        id: 'aws-fault-injection-service',
        label: 'Fault Injection Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["fault","injection","service"],
      },
      {
        id: 'aws-infrastructure-composer',
        label: 'Infrastructure Composer',
        color: '#FF9900',
        source: 'aws',
        tags: ["infrastructure","composer"],
      },
      {
        id: 'aws-tools-and-sdks',
        label: 'Tools and SDKs',
        color: '#FF9900',
        source: 'aws',
        tags: ["tools","and","sdks"],
      },
      {
        id: 'aws-x-ray',
        label: 'X Ray',
        color: '#FF9900',
        source: 'aws',
        tags: ["x","ray"],
      },
      {
        id: 'aws-codecatalyst',
        label: 'CodeCatalyst',
        color: '#FF9900',
        source: 'aws',
        tags: ["codecatalyst"],
      },
      {
        id: 'aws-corretto',
        label: 'Corretto',
        color: '#FF9900',
        source: 'aws',
        tags: ["corretto"],
      },
      {
        id: 'aws-appstream-2',
        label: 'AppStream 2',
        color: '#FF9900',
        source: 'aws',
        tags: ["appstream","2"],
      },
      {
        id: 'aws-workspaces-family',
        label: 'WorkSpaces Family',
        color: '#FF9900',
        source: 'aws',
        tags: ["workspaces","family"],
      },
      {
        id: 'aws-amplify',
        label: 'Amplify',
        color: '#FF9900',
        source: 'aws',
        tags: ["amplify"],
      },
      {
        id: 'aws-device-farm',
        label: 'Device Farm',
        color: '#FF9900',
        source: 'aws',
        tags: ["device","farm"],
      },
      {
        id: 'aws-location-service',
        label: 'Location Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["location","service"],
      },
      {
        id: 'aws-gamelift-servers',
        label: 'GameLift Servers',
        color: '#FF9900',
        source: 'aws',
        tags: ["gamelift","servers"],
      },
      {
        id: 'aws-gamelift-streams',
        label: 'GameLift Streams',
        color: '#FF9900',
        source: 'aws',
        tags: ["gamelift","streams"],
      },
      {
        id: 'aws-open-3d-engine',
        label: 'Open 3D Engine',
        color: '#FF9900',
        source: 'aws',
        tags: ["open","3d","engine"],
      },
      {
        id: 'aws-marketplace_light',
        label: 'Marketplace_Light',
        color: '#FF9900',
        source: 'aws',
        tags: ["marketplace_light"],
      },
      {
        id: 'aws-iot-analytics',
        label: 'IoT Analytics',
        color: '#FF9900',
        source: 'aws',
        tags: ["iot","analytics"],
      },
      {
        id: 'aws-iot-button',
        label: 'IoT Button',
        color: '#FF9900',
        source: 'aws',
        tags: ["iot","button"],
      },
      {
        id: 'aws-iot-core',
        label: 'IoT Core',
        color: '#FF9900',
        source: 'aws',
        tags: ["iot","core"],
      },
      {
        id: 'aws-iot-device-defender',
        label: 'IoT Device Defender',
        color: '#FF9900',
        source: 'aws',
        tags: ["iot","device","defender"],
      },
      {
        id: 'aws-iot-device-management',
        label: 'IoT Device Management',
        color: '#FF9900',
        source: 'aws',
        tags: ["iot","device","management"],
      },
      {
        id: 'aws-iot-events',
        label: 'IoT Events',
        color: '#FF9900',
        source: 'aws',
        tags: ["iot","events"],
      },
      {
        id: 'aws-iot-expresslink',
        label: 'IoT ExpressLink',
        color: '#FF9900',
        source: 'aws',
        tags: ["iot","expresslink"],
      },
      {
        id: 'aws-iot-fleetwise',
        label: 'IoT FleetWise',
        color: '#FF9900',
        source: 'aws',
        tags: ["iot","fleetwise"],
      },
      {
        id: 'aws-iot-greengrass',
        label: 'IoT Greengrass',
        color: '#FF9900',
        source: 'aws',
        tags: ["iot","greengrass"],
      },
      {
        id: 'aws-iot-sitewise',
        label: 'IoT SiteWise',
        color: '#FF9900',
        source: 'aws',
        tags: ["iot","sitewise"],
      },
      {
        id: 'aws-iot-twinmaker',
        label: 'IoT TwinMaker',
        color: '#FF9900',
        source: 'aws',
        tags: ["iot","twinmaker"],
      },
      {
        id: 'aws-freertos',
        label: 'FreeRTOS',
        color: '#FF9900',
        source: 'aws',
        tags: ["freertos"],
      },
      {
        id: 'aws-appconfig',
        label: 'AppConfig',
        color: '#FF9900',
        source: 'aws',
        tags: ["appconfig"],
      },
      {
        id: 'aws-application-auto-scaling',
        label: 'Application Auto Scaling',
        color: '#FF9900',
        source: 'aws',
        tags: ["application","auto","scaling"],
      },
      {
        id: 'aws-auto-scaling',
        label: 'Auto Scaling',
        color: '#FF9900',
        source: 'aws',
        tags: ["auto","scaling"],
      },
      {
        id: 'aws-backint-agent',
        label: 'Backint Agent',
        color: '#FF9900',
        source: 'aws',
        tags: ["backint","agent"],
      },
      {
        id: 'aws-chatbot',
        label: 'Chatbot',
        color: '#FF9900',
        source: 'aws',
        tags: ["chatbot"],
      },
      {
        id: 'aws-cloudformation',
        label: 'CloudFormation',
        color: '#FF9900',
        source: 'aws',
        tags: ["cloudformation"],
      },
      {
        id: 'aws-cloudtrail',
        label: 'CloudTrail',
        color: '#FF9900',
        source: 'aws',
        tags: ["cloudtrail"],
      },
      {
        id: 'aws-config',
        label: 'Config',
        color: '#FF9900',
        source: 'aws',
        tags: ["config"],
      },
      {
        id: 'aws-console-mobile-application',
        label: 'Console Mobile Application',
        color: '#FF9900',
        source: 'aws',
        tags: ["console","mobile","application"],
      },
      {
        id: 'aws-control-tower',
        label: 'Control Tower',
        color: '#FF9900',
        source: 'aws',
        tags: ["control","tower"],
      },
      {
        id: 'aws-distro-for-opentelemetry',
        label: 'Distro for OpenTelemetry',
        color: '#FF9900',
        source: 'aws',
        tags: ["distro","for","opentelemetry"],
      },
      {
        id: 'aws-health-dashboard',
        label: 'Health Dashboard',
        color: '#FF9900',
        source: 'aws',
        tags: ["health","dashboard"],
      },
      {
        id: 'aws-launch-wizard',
        label: 'Launch Wizard',
        color: '#FF9900',
        source: 'aws',
        tags: ["launch","wizard"],
      },
      {
        id: 'aws-license-manager',
        label: 'License Manager',
        color: '#FF9900',
        source: 'aws',
        tags: ["license","manager"],
      },
      {
        id: 'aws-management-console',
        label: 'Management Console',
        color: '#FF9900',
        source: 'aws',
        tags: ["management","console"],
      },
      {
        id: 'aws-organizations',
        label: 'Organizations',
        color: '#FF9900',
        source: 'aws',
        tags: ["organizations"],
      },
      {
        id: 'aws-proton',
        label: 'Proton',
        color: '#FF9900',
        source: 'aws',
        tags: ["proton"],
      },
      {
        id: 'aws-resilience-hub',
        label: 'Resilience Hub',
        color: '#FF9900',
        source: 'aws',
        tags: ["resilience","hub"],
      },
      {
        id: 'aws-resource-explorer',
        label: 'Resource Explorer',
        color: '#FF9900',
        source: 'aws',
        tags: ["resource","explorer"],
      },
      {
        id: 'aws-service-catalog',
        label: 'Service Catalog',
        color: '#FF9900',
        source: 'aws',
        tags: ["service","catalog"],
      },
      {
        id: 'aws-service-management-connector',
        label: 'Service Management Connector',
        color: '#FF9900',
        source: 'aws',
        tags: ["service","management","connector"],
      },
      {
        id: 'aws-systems-manager',
        label: 'Systems Manager',
        color: '#FF9900',
        source: 'aws',
        tags: ["systems","manager"],
      },
      {
        id: 'aws-telco-network-builder',
        label: 'Telco Network Builder',
        color: '#FF9900',
        source: 'aws',
        tags: ["telco","network","builder"],
      },
      {
        id: 'aws-trusted-advisor',
        label: 'Trusted Advisor',
        color: '#FF9900',
        source: 'aws',
        tags: ["trusted","advisor"],
      },
      {
        id: 'aws-user-notifications',
        label: 'User Notifications',
        color: '#FF9900',
        source: 'aws',
        tags: ["user","notifications"],
      },
      {
        id: 'aws-well-architected-tool',
        label: 'Well Architected Tool',
        color: '#FF9900',
        source: 'aws',
        tags: ["well","architected","tool"],
      },
      {
        id: 'aws-cloudwatch',
        label: 'CloudWatch',
        color: '#FF9900',
        source: 'aws',
        tags: ["cloudwatch"],
      },
      {
        id: 'aws-managed-grafana',
        label: 'Managed Grafana',
        color: '#FF9900',
        source: 'aws',
        tags: ["managed","grafana"],
      },
      {
        id: 'aws-managed-service-for-prometheus',
        label: 'Managed Service for Prometheus',
        color: '#FF9900',
        source: 'aws',
        tags: ["managed","service","for","prometheus"],
      },
      {
        id: 'aws-deadline-cloud',
        label: 'Deadline Cloud',
        color: '#FF9900',
        source: 'aws',
        tags: ["deadline","cloud"],
      },
      {
        id: 'aws-elemental-appliances-software',
        label: 'Elemental Appliances & Software',
        color: '#FF9900',
        source: 'aws',
        tags: ["elemental","appliances","&","software"],
      },
      {
        id: 'aws-elemental-conductor',
        label: 'Elemental Conductor',
        color: '#FF9900',
        source: 'aws',
        tags: ["elemental","conductor"],
      },
      {
        id: 'aws-elemental-delta',
        label: 'Elemental Delta',
        color: '#FF9900',
        source: 'aws',
        tags: ["elemental","delta"],
      },
      {
        id: 'aws-elemental-link',
        label: 'Elemental Link',
        color: '#FF9900',
        source: 'aws',
        tags: ["elemental","link"],
      },
      {
        id: 'aws-elemental-live',
        label: 'Elemental Live',
        color: '#FF9900',
        source: 'aws',
        tags: ["elemental","live"],
      },
      {
        id: 'aws-elemental-mediaconnect',
        label: 'Elemental MediaConnect',
        color: '#FF9900',
        source: 'aws',
        tags: ["elemental","mediaconnect"],
      },
      {
        id: 'aws-elemental-mediaconvert',
        label: 'Elemental MediaConvert',
        color: '#FF9900',
        source: 'aws',
        tags: ["elemental","mediaconvert"],
      },
      {
        id: 'aws-elemental-medialive',
        label: 'Elemental MediaLive',
        color: '#FF9900',
        source: 'aws',
        tags: ["elemental","medialive"],
      },
      {
        id: 'aws-elemental-mediapackage',
        label: 'Elemental MediaPackage',
        color: '#FF9900',
        source: 'aws',
        tags: ["elemental","mediapackage"],
      },
      {
        id: 'aws-elemental-mediastore',
        label: 'Elemental MediaStore',
        color: '#FF9900',
        source: 'aws',
        tags: ["elemental","mediastore"],
      },
      {
        id: 'aws-elemental-mediatailor',
        label: 'Elemental MediaTailor',
        color: '#FF9900',
        source: 'aws',
        tags: ["elemental","mediatailor"],
      },
      {
        id: 'aws-elemental-server',
        label: 'Elemental Server',
        color: '#FF9900',
        source: 'aws',
        tags: ["elemental","server"],
      },
      {
        id: 'aws-thinkbox-deadline',
        label: 'Thinkbox Deadline',
        color: '#FF9900',
        source: 'aws',
        tags: ["thinkbox","deadline"],
      },
      {
        id: 'aws-thinkbox-frost',
        label: 'Thinkbox Frost',
        color: '#FF9900',
        source: 'aws',
        tags: ["thinkbox","frost"],
      },
      {
        id: 'aws-thinkbox-krakatoa',
        label: 'Thinkbox Krakatoa',
        color: '#FF9900',
        source: 'aws',
        tags: ["thinkbox","krakatoa"],
      },
      {
        id: 'aws-thinkbox-sequoia',
        label: 'Thinkbox Sequoia',
        color: '#FF9900',
        source: 'aws',
        tags: ["thinkbox","sequoia"],
      },
      {
        id: 'aws-thinkbox-stoke',
        label: 'Thinkbox Stoke',
        color: '#FF9900',
        source: 'aws',
        tags: ["thinkbox","stoke"],
      },
      {
        id: 'aws-thinkbox-xmesh',
        label: 'Thinkbox XMesh',
        color: '#FF9900',
        source: 'aws',
        tags: ["thinkbox","xmesh"],
      },
      {
        id: 'aws-elastic-transcoder',
        label: 'Elastic Transcoder',
        color: '#FF9900',
        source: 'aws',
        tags: ["elastic","transcoder"],
      },
      {
        id: 'aws-interactive-video-service',
        label: 'Interactive Video Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["interactive","video","service"],
      },
      {
        id: 'aws-application-discovery-service',
        label: 'Application Discovery Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["application","discovery","service"],
      },
      {
        id: 'aws-application-migration-service',
        label: 'Application Migration Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["application","migration","service"],
      },
      {
        id: 'aws-data-transfer-terminal',
        label: 'Data Transfer Terminal',
        color: '#FF9900',
        source: 'aws',
        tags: ["data","transfer","terminal"],
      },
      {
        id: 'aws-datasync',
        label: 'DataSync',
        color: '#FF9900',
        source: 'aws',
        tags: ["datasync"],
      },
      {
        id: 'aws-mainframe-modernization',
        label: 'Mainframe Modernization',
        color: '#FF9900',
        source: 'aws',
        tags: ["mainframe","modernization"],
      },
      {
        id: 'aws-migration-evaluator',
        label: 'Migration Evaluator',
        color: '#FF9900',
        source: 'aws',
        tags: ["migration","evaluator"],
      },
      {
        id: 'aws-migration-hub',
        label: 'Migration Hub',
        color: '#FF9900',
        source: 'aws',
        tags: ["migration","hub"],
      },
      {
        id: 'aws-transfer-family',
        label: 'Transfer Family',
        color: '#FF9900',
        source: 'aws',
        tags: ["transfer","family"],
      },
      {
        id: 'aws-transform',
        label: 'Transform',
        color: '#FF9900',
        source: 'aws',
        tags: ["transform"],
      },
      {
        id: 'aws-app-mesh',
        label: 'App Mesh',
        color: '#FF9900',
        source: 'aws',
        tags: ["app","mesh"],
      },
      {
        id: 'aws-client-vpn',
        label: 'Client VPN',
        color: '#FF9900',
        source: 'aws',
        tags: ["client","vpn"],
      },
      {
        id: 'aws-cloud-map',
        label: 'Cloud Map',
        color: '#FF9900',
        source: 'aws',
        tags: ["cloud","map"],
      },
      {
        id: 'aws-cloud-wan',
        label: 'Cloud WAN',
        color: '#FF9900',
        source: 'aws',
        tags: ["cloud","wan"],
      },
      {
        id: 'aws-direct-connect',
        label: 'Direct Connect',
        color: '#FF9900',
        source: 'aws',
        tags: ["direct","connect"],
      },
      {
        id: 'aws-global-accelerator',
        label: 'Global Accelerator',
        color: '#FF9900',
        source: 'aws',
        tags: ["global","accelerator"],
      },
      {
        id: 'aws-private-5g',
        label: 'Private 5G',
        color: '#FF9900',
        source: 'aws',
        tags: ["private","5g"],
      },
      {
        id: 'aws-privatelink',
        label: 'PrivateLink',
        color: '#FF9900',
        source: 'aws',
        tags: ["privatelink"],
      },
      {
        id: 'aws-site-to-site-vpn',
        label: 'Site to Site VPN',
        color: '#FF9900',
        source: 'aws',
        tags: ["site","to","site","vpn"],
      },
      {
        id: 'aws-transit-gateway',
        label: 'Transit Gateway',
        color: '#FF9900',
        source: 'aws',
        tags: ["transit","gateway"],
      },
      {
        id: 'aws-verified-access',
        label: 'Verified Access',
        color: '#FF9900',
        source: 'aws',
        tags: ["verified","access"],
      },
      {
        id: 'aws-api-gateway',
        label: 'API Gateway',
        color: '#FF9900',
        source: 'aws',
        tags: ["api","gateway"],
      },
      {
        id: 'aws-application-recovery-controller',
        label: 'Application Recovery Controller',
        color: '#FF9900',
        source: 'aws',
        tags: ["application","recovery","controller"],
      },
      {
        id: 'aws-cloudfront',
        label: 'CloudFront',
        color: '#FF9900',
        source: 'aws',
        tags: ["cloudfront"],
      },
      {
        id: 'aws-route-53',
        label: 'Route 53',
        color: '#FF9900',
        source: 'aws',
        tags: ["route","53"],
      },
      {
        id: 'aws-vpc-lattice',
        label: 'VPC Lattice',
        color: '#FF9900',
        source: 'aws',
        tags: ["vpc","lattice"],
      },
      {
        id: 'aws-virtual-private-cloud',
        label: 'Virtual Private Cloud',
        color: '#FF9900',
        source: 'aws',
        tags: ["virtual","private","cloud"],
      },
      {
        id: 'aws-elastic-load-balancing',
        label: 'Elastic Load Balancing',
        color: '#FF9900',
        source: 'aws',
        tags: ["elastic","load","balancing"],
      },
      {
        id: 'aws-braket',
        label: 'Braket',
        color: '#FF9900',
        source: 'aws',
        tags: ["braket"],
      },
      {
        id: 'aws-ground-station',
        label: 'Ground Station',
        color: '#FF9900',
        source: 'aws',
        tags: ["ground","station"],
      },
      {
        id: 'aws-artifact',
        label: 'Artifact',
        color: '#FF9900',
        source: 'aws',
        tags: ["artifact"],
      },
      {
        id: 'aws-audit-manager',
        label: 'Audit Manager',
        color: '#FF9900',
        source: 'aws',
        tags: ["audit","manager"],
      },
      {
        id: 'aws-certificate-manager',
        label: 'Certificate Manager',
        color: '#FF9900',
        source: 'aws',
        tags: ["certificate","manager"],
      },
      {
        id: 'aws-cloudhsm',
        label: 'CloudHSM',
        color: '#FF9900',
        source: 'aws',
        tags: ["cloudhsm"],
      },
      {
        id: 'aws-directory-service',
        label: 'Directory Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["directory","service"],
      },
      {
        id: 'aws-firewall-manager',
        label: 'Firewall Manager',
        color: '#FF9900',
        source: 'aws',
        tags: ["firewall","manager"],
      },
      {
        id: 'aws-iam-identity-center',
        label: 'IAM Identity Center',
        color: '#FF9900',
        source: 'aws',
        tags: ["iam","identity","center"],
      },
      {
        id: 'aws-identity-and-access-management',
        label: 'Identity and Access Management',
        color: '#FF9900',
        source: 'aws',
        tags: ["identity","and","access","management"],
      },
      {
        id: 'aws-key-management-service',
        label: 'Key Management Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["key","management","service"],
      },
      {
        id: 'aws-network-firewall',
        label: 'Network Firewall',
        color: '#FF9900',
        source: 'aws',
        tags: ["network","firewall"],
      },
      {
        id: 'aws-payment-cryptography',
        label: 'Payment Cryptography',
        color: '#FF9900',
        source: 'aws',
        tags: ["payment","cryptography"],
      },
      {
        id: 'aws-private-certificate-authority',
        label: 'Private Certificate Authority',
        color: '#FF9900',
        source: 'aws',
        tags: ["private","certificate","authority"],
      },
      {
        id: 'aws-resource-access-manager',
        label: 'Resource Access Manager',
        color: '#FF9900',
        source: 'aws',
        tags: ["resource","access","manager"],
      },
      {
        id: 'aws-secrets-manager',
        label: 'Secrets Manager',
        color: '#FF9900',
        source: 'aws',
        tags: ["secrets","manager"],
      },
      {
        id: 'aws-security-hub',
        label: 'Security Hub',
        color: '#FF9900',
        source: 'aws',
        tags: ["security","hub"],
      },
      {
        id: 'aws-security-incident-response',
        label: 'Security Incident Response',
        color: '#FF9900',
        source: 'aws',
        tags: ["security","incident","response"],
      },
      {
        id: 'aws-shield',
        label: 'Shield',
        color: '#FF9900',
        source: 'aws',
        tags: ["shield"],
      },
      {
        id: 'aws-signer',
        label: 'Signer',
        color: '#FF9900',
        source: 'aws',
        tags: ["signer"],
      },
      {
        id: 'aws-waf',
        label: 'WAF',
        color: '#FF9900',
        source: 'aws',
        tags: ["waf"],
      },
      {
        id: 'aws-cloud-directory',
        label: 'Cloud Directory',
        color: '#FF9900',
        source: 'aws',
        tags: ["cloud","directory"],
      },
      {
        id: 'aws-cognito',
        label: 'Cognito',
        color: '#FF9900',
        source: 'aws',
        tags: ["cognito"],
      },
      {
        id: 'aws-detective',
        label: 'Detective',
        color: '#FF9900',
        source: 'aws',
        tags: ["detective"],
      },
      {
        id: 'aws-guardduty',
        label: 'GuardDuty',
        color: '#FF9900',
        source: 'aws',
        tags: ["guardduty"],
      },
      {
        id: 'aws-inspector',
        label: 'Inspector',
        color: '#FF9900',
        source: 'aws',
        tags: ["inspector"],
      },
      {
        id: 'aws-macie',
        label: 'Macie',
        color: '#FF9900',
        source: 'aws',
        tags: ["macie"],
      },
      {
        id: 'aws-security-lake',
        label: 'Security Lake',
        color: '#FF9900',
        source: 'aws',
        tags: ["security","lake"],
      },
      {
        id: 'aws-verified-permissions',
        label: 'Verified Permissions',
        color: '#FF9900',
        source: 'aws',
        tags: ["verified","permissions"],
      },
      {
        id: 'aws-backup',
        label: 'Backup',
        color: '#FF9900',
        source: 'aws',
        tags: ["backup"],
      },
      {
        id: 'aws-elastic-disaster-recovery',
        label: 'Elastic Disaster Recovery',
        color: '#FF9900',
        source: 'aws',
        tags: ["elastic","disaster","recovery"],
      },
      {
        id: 'aws-snowball-edge',
        label: 'Snowball Edge',
        color: '#FF9900',
        source: 'aws',
        tags: ["snowball","edge"],
      },
      {
        id: 'aws-snowball',
        label: 'Snowball',
        color: '#FF9900',
        source: 'aws',
        tags: ["snowball"],
      },
      {
        id: 'aws-storage-gateway',
        label: 'Storage Gateway',
        color: '#FF9900',
        source: 'aws',
        tags: ["storage","gateway"],
      },
      {
        id: 'aws-efs',
        label: 'EFS',
        color: '#FF9900',
        source: 'aws',
        tags: ["efs"],
      },
      {
        id: 'aws-elastic-block-store',
        label: 'Elastic Block Store',
        color: '#FF9900',
        source: 'aws',
        tags: ["elastic","block","store"],
      },
      {
        id: 'aws-fsx-for-lustre',
        label: 'FSx for Lustre',
        color: '#FF9900',
        source: 'aws',
        tags: ["fsx","for","lustre"],
      },
      {
        id: 'aws-fsx-for-netapp-ontap',
        label: 'FSx for NetApp ONTAP',
        color: '#FF9900',
        source: 'aws',
        tags: ["fsx","for","netapp","ontap"],
      },
      {
        id: 'aws-fsx-for-openzfs',
        label: 'FSx for OpenZFS',
        color: '#FF9900',
        source: 'aws',
        tags: ["fsx","for","openzfs"],
      },
      {
        id: 'aws-fsx-for-wfs',
        label: 'FSx for WFS',
        color: '#FF9900',
        source: 'aws',
        tags: ["fsx","for","wfs"],
      },
      {
        id: 'aws-fsx',
        label: 'FSx',
        color: '#FF9900',
        source: 'aws',
        tags: ["fsx"],
      },
      {
        id: 'aws-file-cache',
        label: 'File Cache',
        color: '#FF9900',
        source: 'aws',
        tags: ["file","cache"],
      },
      {
        id: 'aws-s3-on-outposts',
        label: 'S3 on Outposts',
        color: '#FF9900',
        source: 'aws',
        tags: ["s3","on","outposts"],
      },
      {
        id: 'aws-simple-storage-service-glacier',
        label: 'Simple Storage Service Glacier',
        color: '#FF9900',
        source: 'aws',
        tags: ["simple","storage","service","glacier"],
      },
      {
        id: 'aws-simple-storage-service',
        label: 'Simple Storage Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["simple","storage","service"],
      }
    ],
  }
];

/**
 * AWS categories as a Record
 */
export const awsCategories: Record<string, IconCategory> = Object.fromEntries(
  awsCategoriesArray.map((cat) => [cat.label, cat])
);

/**
 * Get all AWS icons
 */
export const getAllAwsIcons = () => {
  return awsCategoriesArray.flatMap((cat) => cat.icons);
};

export default awsCategoriesArray;
