/**
 * AWS Icon Categories - Auto-generated from aws-react-icons
 *
 * This file is auto-generated from the aws-react-icons library (awsicons.dev).
 * To regenerate, run: node scripts/generate-aws-from-library.js
 *
 * Total icons: 319
 * Total categories: 23
 */

import type { IconCategory } from '../types';

const awsCategoriesArray: IconCategory[] = [
  {
    label: 'Compute',
    source: 'aws',
    icons: [
      {
        id: 'aws-aws-app-runner',
        label: 'AWS App Runner',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","app","runner"],
      },
      {
        id: 'aws-aws-batch',
        label: 'AWS Batch',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","batch"],
      },
      {
        id: 'aws-aws-compute-optimizer',
        label: 'AWS Compute Optimizer',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","compute","optimizer"],
      },
      {
        id: 'aws-aws-elastic-beanstalk',
        label: 'AWS Elastic Beanstalk',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","elastic","beanstalk"],
      },
      {
        id: 'aws-aws-fargate',
        label: 'AWS Fargate',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","fargate"],
      },
      {
        id: 'aws-aws-lambda',
        label: 'AWS Lambda',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","lambda"],
      },
      {
        id: 'aws-aws-nitro-enclaves',
        label: 'AWS Nitro Enclaves',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","nitro","enclaves"],
      },
      {
        id: 'aws-aws-outpostsfamily',
        label: 'AWS Outpostsfamily',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","outpostsfamily"],
      },
      {
        id: 'aws-aws-outpostsrack',
        label: 'AWS Outpostsrack',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","outpostsrack"],
      },
      {
        id: 'aws-aws-outpostsservers',
        label: 'AWS Outpostsservers',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","outpostsservers"],
      },
      {
        id: 'aws-aws-parallel-cluster',
        label: 'AWS Parallel Cluster',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","parallel","cluster"],
      },
      {
        id: 'aws-aws-parallel-computing-service',
        label: 'AWS Parallel Computing Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","parallel","computing","service"],
      },
      {
        id: 'aws-aws-serverless-application-repository',
        label: 'AWS Serverless Application Repository',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","serverless","application","repository"],
      },
      {
        id: 'aws-aws-thinkbox-deadline',
        label: 'AWS Thinkbox Deadline',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","thinkbox","deadline"],
      },
      {
        id: 'aws-aws-thinkbox-frost',
        label: 'AWS Thinkbox Frost',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","thinkbox","frost"],
      },
      {
        id: 'aws-aws-thinkbox-krakatoa',
        label: 'AWS Thinkbox Krakatoa',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","thinkbox","krakatoa"],
      },
      {
        id: 'aws-aws-thinkbox-sequoia',
        label: 'AWS Thinkbox Sequoia',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","thinkbox","sequoia"],
      },
      {
        id: 'aws-aws-thinkbox-stoke',
        label: 'AWS Thinkbox Stoke',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","thinkbox","stoke"],
      },
      {
        id: 'aws-aws-thinkbox-x-mesh',
        label: 'AWS Thinkbox X Mesh',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","thinkbox","mesh"],
      },
      {
        id: 'aws-aws-wavelength',
        label: 'AWS Wavelength',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","wavelength"],
      },
      {
        id: 'aws-amazon-ec2',
        label: 'Amazon EC 2',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","ec"],
      },
      {
        id: 'aws-amazon-ec2auto-scaling',
        label: 'Amazon EC 2 Auto Scaling',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","ec","auto","scaling"],
      },
      {
        id: 'aws-amazon-ec2image-builder',
        label: 'Amazon EC 2 Image Builder',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","ec","image","builder"],
      },
      {
        id: 'aws-amazon-elastic-v-mware-service',
        label: 'Amazon Elastic V Mware Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","elastic","mware","service"],
      },
      {
        id: 'aws-amazon-lightsail',
        label: 'Amazon Lightsail',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","lightsail"],
      },
      {
        id: 'aws-amazon-lightsailfor-research',
        label: 'Amazon Lightsailfor Research',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","lightsailfor","research"],
      },
      {
        id: 'aws-amazon-monitron',
        label: 'Amazon Monitron',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","monitron"],
      },
      {
        id: 'aws-amazon-s3on-outposts',
        label: 'Amazon S3 on Outposts',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","s3","on","outposts"],
      },
      {
        id: 'aws-bottlerocket',
        label: 'Bottlerocket',
        color: '#FF9900',
        source: 'aws',
        tags: ["bottlerocket"],
      }
    ],
  },
  {
    label: 'Security & Identity',
    source: 'aws',
    icons: [
      {
        id: 'aws-aws-artifact',
        label: 'AWS Artifact',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","artifact"],
      },
      {
        id: 'aws-aws-certificate-manager',
        label: 'AWS Certificate Manager',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","certificate","manager"],
      },
      {
        id: 'aws-aws-cloud-hsm',
        label: 'AWS Cloud HSM',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","cloud","hsm"],
      },
      {
        id: 'aws-aws-code-artifact',
        label: 'AWS Code Artifact',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","code","artifact"],
      },
      {
        id: 'aws-aws-directory-service',
        label: 'AWS Directory Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","directory","service"],
      },
      {
        id: 'aws-aws-elemental-appliances-software',
        label: 'AWS Elemental Appliances Software',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","elemental","appliances","software"],
      },
      {
        id: 'aws-aws-firewall-manager',
        label: 'AWS Firewall Manager',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","firewall","manager"],
      },
      {
        id: 'aws-awsiam-identity-center',
        label: 'AWSIAM Identity Center',
        color: '#FF9900',
        source: 'aws',
        tags: ["awsiam","identity","center"],
      },
      {
        id: 'aws-aws-identityand-access-management',
        label: 'AWS Identityand Access Management',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","identityand","access","management"],
      },
      {
        id: 'aws-aws-mainframe-modernization',
        label: 'AWS Mainframe Modernization',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","mainframe","modernization"],
      },
      {
        id: 'aws-aws-panorama',
        label: 'AWS Panorama',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","panorama"],
      },
      {
        id: 'aws-aws-payment-cryptography',
        label: 'AWS Payment Cryptography',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","payment","cryptography"],
      },
      {
        id: 'aws-aws-private-certificate-authority',
        label: 'AWS Private Certificate Authority',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","private","certificate","authority"],
      },
      {
        id: 'aws-aws-resource-access-manager',
        label: 'AWS Resource Access Manager',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","resource","access","manager"],
      },
      {
        id: 'aws-aws-security-hub',
        label: 'AWS Security Hub',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","security","hub"],
      },
      {
        id: 'aws-aws-security-incident-response',
        label: 'AWS Security Incident Response',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","security","incident","response"],
      },
      {
        id: 'aws-aws-shield',
        label: 'AWS Shield',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","shield"],
      },
      {
        id: 'aws-aws-signer',
        label: 'AWS Signer',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","signer"],
      },
      {
        id: 'aws-aws-verified-access',
        label: 'AWS Verified Access',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","verified","access"],
      },
      {
        id: 'aws-awswaf',
        label: 'AWSWAF',
        color: '#FF9900',
        source: 'aws',
        tags: ["awswaf"],
      },
      {
        id: 'aws-amazon-cloud-directory',
        label: 'Amazon Cloud Directory',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","cloud","directory"],
      },
      {
        id: 'aws-amazon-cognito',
        label: 'Amazon Cognito',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","cognito"],
      },
      {
        id: 'aws-amazon-detective',
        label: 'Amazon Detective',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","detective"],
      },
      {
        id: 'aws-amazon-guard-duty',
        label: 'Amazon Guard Duty',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","guard","duty"],
      },
      {
        id: 'aws-amazon-inspector',
        label: 'Amazon Inspector',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","inspector"],
      },
      {
        id: 'aws-amazon-macie',
        label: 'Amazon Macie',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","macie"],
      },
      {
        id: 'aws-amazon-security-lake',
        label: 'Amazon Security Lake',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","security","lake"],
      },
      {
        id: 'aws-nice-engin-frame',
        label: 'NICE Engin Frame',
        color: '#FF9900',
        source: 'aws',
        tags: ["nice","engin","frame"],
      }
    ],
  },
  {
    label: 'Machine Learning & AI',
    source: 'aws',
    icons: [
      {
        id: 'aws-aws-deep-composer',
        label: 'AWS Deep Composer',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","deep","composer"],
      },
      {
        id: 'aws-aws-deep-racer',
        label: 'AWS Deep Racer',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","deep","racer"],
      },
      {
        id: 'aws-aws-health-lake',
        label: 'AWS Health Lake',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","health","lake"],
      },
      {
        id: 'aws-aws-health-omics',
        label: 'AWS Health Omics',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","health","omics"],
      },
      {
        id: 'aws-aws-neuron',
        label: 'AWS Neuron',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","neuron"],
      },
      {
        id: 'aws-alexa-for-business',
        label: 'Alexa For Business',
        color: '#FF9900',
        source: 'aws',
        tags: ["alexa","for","business"],
      },
      {
        id: 'aws-amazon-augmented-aia2i',
        label: 'Amazon Augmented AIA 2 I',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","augmented","aia"],
      },
      {
        id: 'aws-amazon-bedrock',
        label: 'Amazon Bedrock',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","bedrock"],
      },
      {
        id: 'aws-amazon-code-whisperer',
        label: 'Amazon Code Whisperer',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","code","whisperer"],
      },
      {
        id: 'aws-amazon-comprehend',
        label: 'Amazon Comprehend',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","comprehend"],
      },
      {
        id: 'aws-amazon-comprehend-medical',
        label: 'Amazon Comprehend Medical',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","comprehend","medical"],
      },
      {
        id: 'aws-amazon-forecast',
        label: 'Amazon Forecast',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","forecast"],
      },
      {
        id: 'aws-amazon-fraud-detector',
        label: 'Amazon Fraud Detector',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","fraud","detector"],
      },
      {
        id: 'aws-amazon-kendra',
        label: 'Amazon Kendra',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","kendra"],
      },
      {
        id: 'aws-amazon-lex',
        label: 'Amazon Lex',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","lex"],
      },
      {
        id: 'aws-amazon-lookoutfor-equipment',
        label: 'Amazon Lookoutfor Equipment',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","lookoutfor","equipment"],
      },
      {
        id: 'aws-amazon-lookoutfor-metrics',
        label: 'Amazon Lookoutfor Metrics',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","lookoutfor","metrics"],
      },
      {
        id: 'aws-amazon-lookoutfor-vision',
        label: 'Amazon Lookoutfor Vision',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","lookoutfor","vision"],
      },
      {
        id: 'aws-amazon-personalize',
        label: 'Amazon Personalize',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","personalize"],
      },
      {
        id: 'aws-amazon-polly',
        label: 'Amazon Polly',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","polly"],
      },
      {
        id: 'aws-amazon-rekognition',
        label: 'Amazon Rekognition',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","rekognition"],
      },
      {
        id: 'aws-amazon-sage-maker',
        label: 'Amazon Sage Maker',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","sage","maker"],
      },
      {
        id: 'aws-amazon-sage-maker-ai',
        label: 'Amazon Sage Maker AI',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","sage","maker","ai"],
      },
      {
        id: 'aws-amazon-sage-maker-ground-truth',
        label: 'Amazon Sage Maker Ground Truth',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","sage","maker","ground","truth"],
      },
      {
        id: 'aws-amazon-sage-maker-studio-lab',
        label: 'Amazon Sage Maker Studio Lab',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","sage","maker","studio","lab"],
      },
      {
        id: 'aws-amazon-textract',
        label: 'Amazon Textract',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","textract"],
      },
      {
        id: 'aws-amazon-transcribe',
        label: 'Amazon Transcribe',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","transcribe"],
      },
      {
        id: 'aws-amazon-translate',
        label: 'Amazon Translate',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","translate"],
      }
    ],
  },
  {
    label: 'Management & Governance',
    source: 'aws',
    icons: [
      {
        id: 'aws-aws-app-config',
        label: 'AWS App Config',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","app","config"],
      },
      {
        id: 'aws-aws-billing-conductor',
        label: 'AWS Billing Conductor',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","billing","conductor"],
      },
      {
        id: 'aws-aws-budgets',
        label: 'AWS Budgets',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","budgets"],
      },
      {
        id: 'aws-aws-chatbot',
        label: 'AWS Chatbot',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","chatbot"],
      },
      {
        id: 'aws-aws-cloud-formation',
        label: 'AWS Cloud Formation',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","cloud","formation"],
      },
      {
        id: 'aws-aws-cloud-trail',
        label: 'AWS Cloud Trail',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","cloud","trail"],
      },
      {
        id: 'aws-aws-config',
        label: 'AWS Config',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","config"],
      },
      {
        id: 'aws-aws-control-tower',
        label: 'AWS Control Tower',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","control","tower"],
      },
      {
        id: 'aws-aws-cost-explorer',
        label: 'AWS Cost Explorer',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","cost","explorer"],
      },
      {
        id: 'aws-aws-health-dashboard',
        label: 'AWS Health Dashboard',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","health","dashboard"],
      },
      {
        id: 'aws-aws-launch-wizard',
        label: 'AWS Launch Wizard',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","launch","wizard"],
      },
      {
        id: 'aws-aws-license-manager',
        label: 'AWS License Manager',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","license","manager"],
      },
      {
        id: 'aws-aws-organizations',
        label: 'AWS Organizations',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","organizations"],
      },
      {
        id: 'aws-aws-proton',
        label: 'AWS Proton',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","proton"],
      },
      {
        id: 'aws-aws-resilience-hub',
        label: 'AWS Resilience Hub',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","resilience","hub"],
      },
      {
        id: 'aws-aws-resource-explorer',
        label: 'AWS Resource Explorer',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","resource","explorer"],
      },
      {
        id: 'aws-aws-service-catalog',
        label: 'AWS Service Catalog',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","service","catalog"],
      },
      {
        id: 'aws-aws-systems-manager',
        label: 'AWS Systems Manager',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","systems","manager"],
      },
      {
        id: 'aws-aws-trusted-advisor',
        label: 'AWS Trusted Advisor',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","trusted","advisor"],
      },
      {
        id: 'aws-aws-well-architected-tool',
        label: 'AWS Well Architected Tool',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","well","architected","tool"],
      },
      {
        id: 'aws-amazon-cloud-watch',
        label: 'Amazon Cloud Watch',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","cloud","watch"],
      },
      {
        id: 'aws-amazon-managed-grafana',
        label: 'Amazon Managed Grafana',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","managed","grafana"],
      }
    ],
  },
  {
    label: 'Networking',
    source: 'aws',
    icons: [
      {
        id: 'aws-aws-app-mesh',
        label: 'AWS App Mesh',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","app","mesh"],
      },
      {
        id: 'aws-aws-client-vpn',
        label: 'AWS CLIent VPN',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","client","vpn"],
      },
      {
        id: 'aws-aws-cloud-map',
        label: 'AWS Cloud Map',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","cloud","map"],
      },
      {
        id: 'aws-aws-cloud-wan',
        label: 'AWS Cloud WAN',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","cloud","wan"],
      },
      {
        id: 'aws-aws-direct-connect',
        label: 'AWS Direct Connect',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","direct","connect"],
      },
      {
        id: 'aws-aws-global-accelerator',
        label: 'AWS Global Accelerator',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","global","accelerator"],
      },
      {
        id: 'aws-aws-network-firewall',
        label: 'AWS Network Firewall',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","network","firewall"],
      },
      {
        id: 'aws-aws-private-link',
        label: 'AWS Private Link',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","private","link"],
      },
      {
        id: 'aws-aws-siteto-site-vpn',
        label: 'AWS Siteto Site VPN',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","siteto","site","vpn"],
      },
      {
        id: 'aws-aws-telco-network-builder',
        label: 'AWS Telco Network Builder',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","telco","network","builder"],
      },
      {
        id: 'aws-aws-transit-gateway',
        label: 'AWS Transit Gateway',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","transit","gateway"],
      },
      {
        id: 'aws-amazon-api-gateway',
        label: 'Amazon API Gateway',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","api","gateway"],
      },
      {
        id: 'aws-amazon-athena',
        label: 'Amazon Athena',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","athena"],
      },
      {
        id: 'aws-amazon-cloud-front',
        label: 'Amazon Cloud Front',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","cloud","front"],
      },
      {
        id: 'aws-amazon-route53',
        label: 'Amazon Route 53',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","route","53"],
      },
      {
        id: 'aws-amazon-vpc-lattice',
        label: 'Amazon VPC Lattice',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","vpc","lattice"],
      },
      {
        id: 'aws-elastic-load-balancing',
        label: 'Elastic Load Balancing',
        color: '#FF9900',
        source: 'aws',
        tags: ["elastic","load","balancing"],
      }
    ],
  },
  {
    label: 'Storage',
    source: 'aws',
    icons: [
      {
        id: 'aws-aws-backup',
        label: 'AWS Backup',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","backup"],
      },
      {
        id: 'aws-aws-elastic-disaster-recovery',
        label: 'AWS Elastic Disaster Recovery',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","elastic","disaster","recovery"],
      },
      {
        id: 'aws-aws-snowball',
        label: 'AWS Snowball',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","snowball"],
      },
      {
        id: 'aws-aws-snowball-edge',
        label: 'AWS Snowball Edge',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","snowball","edge"],
      },
      {
        id: 'aws-aws-storage-gateway',
        label: 'AWS Storage Gateway',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","storage","gateway"],
      },
      {
        id: 'aws-amazon-efs',
        label: 'Amazon EFS',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","efs"],
      },
      {
        id: 'aws-amazon-elastic-block-store',
        label: 'Amazon Elastic Block Store',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","elastic","block","store"],
      },
      {
        id: 'aws-amazon-f-sx',
        label: 'Amazon F Sx',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","sx"],
      },
      {
        id: 'aws-amazon-f-sxfor-lustre',
        label: 'Amazon F Sxfor Lustre',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","sxfor","lustre"],
      },
      {
        id: 'aws-amazon-f-sxfor-net-app-ontap',
        label: 'Amazon F Sxfor Net App ONTAP',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","sxfor","net","app","ontap"],
      },
      {
        id: 'aws-amazon-f-sxfor-open-zfs',
        label: 'Amazon F Sxfor Open ZFS',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","sxfor","open","zfs"],
      },
      {
        id: 'aws-amazon-f-sxfor-wfs',
        label: 'Amazon F Sxfor WFS',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","sxfor","wfs"],
      },
      {
        id: 'aws-amazon-file-cache',
        label: 'Amazon File Cache',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","file","cache"],
      },
      {
        id: 'aws-amazon-simple-storage-service',
        label: 'Amazon Simple Storage Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","simple","storage","service"],
      },
      {
        id: 'aws-amazon-simple-storage-service-glacier',
        label: 'Amazon Simple Storage Service Glacier',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","simple","storage","service","glacier"],
      }
    ],
  },
  {
    label: 'Analytics',
    source: 'aws',
    icons: [
      {
        id: 'aws-aws-clean-rooms',
        label: 'AWS Clean Rooms',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","clean","rooms"],
      },
      {
        id: 'aws-aws-data-exchange',
        label: 'AWS Data Exchange',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","data","exchange"],
      },
      {
        id: 'aws-aws-entity-resolution',
        label: 'AWS Entity Resolution',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","entity","resolution"],
      },
      {
        id: 'aws-aws-glue',
        label: 'AWS Glue',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","glue"],
      },
      {
        id: 'aws-aws-glue-data-brew',
        label: 'AWS Glue Data Brew',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","glue","data","brew"],
      },
      {
        id: 'aws-aws-io-t-analytics',
        label: 'AWS Io T Analytics',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","io","analytics"],
      },
      {
        id: 'aws-aws-lake-formation',
        label: 'AWS Lake Formation',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","lake","formation"],
      },
      {
        id: 'aws-amazon-data-zone',
        label: 'Amazon Data Zone',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","data","zone"],
      },
      {
        id: 'aws-amazon-emr',
        label: 'Amazon EMR',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","emr"],
      },
      {
        id: 'aws-amazon-fin-space',
        label: 'Amazon Fin Space',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","fin","space"],
      },
      {
        id: 'aws-amazon-kinesis',
        label: 'Amazon Kinesis',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","kinesis"],
      },
      {
        id: 'aws-amazon-kinesis-data-streams',
        label: 'Amazon Kinesis Data Streams',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","kinesis","data","streams"],
      },
      {
        id: 'aws-amazon-kinesis-video-streams',
        label: 'Amazon Kinesis Video Streams',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","kinesis","video","streams"],
      },
      {
        id: 'aws-amazon-open-search-service',
        label: 'Amazon Open Search Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","open","search","service"],
      },
      {
        id: 'aws-amazon-quick-sight',
        label: 'Amazon Quick Sight',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","quick","sight"],
      }
    ],
  },
  {
    label: 'Media',
    source: 'aws',
    icons: [
      {
        id: 'aws-aws-deadline-cloud',
        label: 'AWS Deadline Cloud',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","deadline","cloud"],
      },
      {
        id: 'aws-aws-elemental-conductor',
        label: 'AWS Elemental Conductor',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","elemental","conductor"],
      },
      {
        id: 'aws-aws-elemental-delta',
        label: 'AWS Elemental Delta',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","elemental","delta"],
      },
      {
        id: 'aws-aws-elemental-link',
        label: 'AWS Elemental Link',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","elemental","link"],
      },
      {
        id: 'aws-aws-elemental-live',
        label: 'AWS Elemental Live',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","elemental","live"],
      },
      {
        id: 'aws-aws-elemental-media-connect',
        label: 'AWS Elemental Media Connect',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","elemental","media","connect"],
      },
      {
        id: 'aws-aws-elemental-media-convert',
        label: 'AWS Elemental Media Convert',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","elemental","media","convert"],
      },
      {
        id: 'aws-aws-elemental-media-live',
        label: 'AWS Elemental Media Live',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","elemental","media","live"],
      },
      {
        id: 'aws-aws-elemental-media-package',
        label: 'AWS Elemental Media Package',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","elemental","media","package"],
      },
      {
        id: 'aws-aws-elemental-media-store',
        label: 'AWS Elemental Media Store',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","elemental","media","store"],
      },
      {
        id: 'aws-aws-elemental-media-tailor',
        label: 'AWS Elemental Media Tailor',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","elemental","media","tailor"],
      },
      {
        id: 'aws-aws-elemental-server',
        label: 'AWS Elemental Server',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","elemental","server"],
      },
      {
        id: 'aws-amazon-elastic-transcoder',
        label: 'Amazon Elastic Transcoder',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","elastic","transcoder"],
      },
      {
        id: 'aws-amazon-interactive-video-service',
        label: 'Amazon Interactive Video Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","interactive","video","service"],
      },
      {
        id: 'aws-amazon-managed-streamingfor-apache-kafka',
        label: 'Amazon Managed Streamingfor Apache Kafka',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","managed","streamingfor","apache","kafka"],
      }
    ],
  },
  {
    label: 'Database',
    source: 'aws',
    icons: [
      {
        id: 'aws-aws-database-migration-service',
        label: 'AWS Database Migration Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","database","migration","service"],
      },
      {
        id: 'aws-amazon-aurora',
        label: 'Amazon Aurora',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","aurora"],
      },
      {
        id: 'aws-amazon-document-db',
        label: 'Amazon Document DB',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","document","db"],
      },
      {
        id: 'aws-amazon-dynamo-db',
        label: 'Amazon Dynamo DB',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","dynamo","db"],
      },
      {
        id: 'aws-amazon-elasti-cache',
        label: 'Amazon Elasti Cache',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","elasti","cache"],
      },
      {
        id: 'aws-amazon-keyspaces',
        label: 'Amazon Keyspaces',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","keyspaces"],
      },
      {
        id: 'aws-amazon-memory-db',
        label: 'Amazon Memory DB',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","memory","db"],
      },
      {
        id: 'aws-amazon-neptune',
        label: 'Amazon Neptune',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","neptune"],
      },
      {
        id: 'aws-amazon-quantum-ledger-database',
        label: 'Amazon Quantum Ledger Database',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","quantum","ledger","database"],
      },
      {
        id: 'aws-amazon-rds',
        label: 'Amazon RDS',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","rds"],
      },
      {
        id: 'aws-amazon-redshift',
        label: 'Amazon Redshift',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","redshift"],
      },
      {
        id: 'aws-amazon-timestream',
        label: 'Amazon Timestream',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","timestream"],
      },
      {
        id: 'aws-oracle-databaseat-aws',
        label: 'Oracle Databaseat AWS',
        color: '#FF9900',
        source: 'aws',
        tags: ["oracle","databaseat","aws"],
      }
    ],
  },
  {
    label: 'Developer Tools',
    source: 'aws',
    icons: [
      {
        id: 'aws-aws-cloud9',
        label: 'AWS Cloud 9',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","cloud"],
      },
      {
        id: 'aws-aws-cloud-shell',
        label: 'AWS Cloud Shell',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","cloud","shell"],
      },
      {
        id: 'aws-aws-code-build',
        label: 'AWS Code Build',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","code","build"],
      },
      {
        id: 'aws-aws-code-commit',
        label: 'AWS Code Commit',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","code","commit"],
      },
      {
        id: 'aws-aws-code-deploy',
        label: 'AWS Code Deploy',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","code","deploy"],
      },
      {
        id: 'aws-aws-code-pipeline',
        label: 'AWS Code Pipeline',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","code","pipeline"],
      },
      {
        id: 'aws-aws-command-line-interface',
        label: 'AWS Command Line Interface',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","command","line","interface"],
      },
      {
        id: 'aws-aws-fault-injection-service',
        label: 'AWS Fault Injection Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","fault","injection","service"],
      },
      {
        id: 'aws-awsx-ray',
        label: 'AWSX Ray',
        color: '#FF9900',
        source: 'aws',
        tags: ["awsx","ray"],
      },
      {
        id: 'aws-amazon-code-catalyst',
        label: 'Amazon Code Catalyst',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","code","catalyst"],
      },
      {
        id: 'aws-amazon-code-guru',
        label: 'Amazon Code Guru',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","code","guru"],
      },
      {
        id: 'aws-amazon-corretto',
        label: 'Amazon Corretto',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","corretto"],
      }
    ],
  },
  {
    label: 'IoT',
    source: 'aws',
    icons: [
      {
        id: 'aws-aws-io-t-button',
        label: 'AWS Io T Button',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","io","button"],
      },
      {
        id: 'aws-aws-io-t-core',
        label: 'AWS Io T Core',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","io","core"],
      },
      {
        id: 'aws-aws-io-t-device-defender',
        label: 'AWS Io T Device Defender',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","io","device","defender"],
      },
      {
        id: 'aws-aws-io-t-device-management',
        label: 'AWS Io T Device Management',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","io","device","management"],
      },
      {
        id: 'aws-aws-io-t-events',
        label: 'AWS Io T Events',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","io","events"],
      },
      {
        id: 'aws-aws-io-t-express-link',
        label: 'AWS Io T Express Link',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","io","express","link"],
      },
      {
        id: 'aws-aws-io-t-fleet-wise',
        label: 'AWS Io T Fleet Wise',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","io","fleet","wise"],
      },
      {
        id: 'aws-aws-io-t-greengrass',
        label: 'AWS Io T Greengrass',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","io","greengrass"],
      },
      {
        id: 'aws-aws-io-t-site-wise',
        label: 'AWS Io T Site Wise',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","io","site","wise"],
      },
      {
        id: 'aws-aws-io-t-twin-maker',
        label: 'AWS Io T Twin Maker',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","io","twin","maker"],
      }
    ],
  },
  {
    label: 'Application Integration',
    source: 'aws',
    icons: [
      {
        id: 'aws-awsb2b-data-interchange',
        label: 'AWSB 2 B Data Interchange',
        color: '#FF9900',
        source: 'aws',
        tags: ["awsb","data","interchange"],
      },
      {
        id: 'aws-aws-express-workflows',
        label: 'AWS Express Workflows',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","express","workflows"],
      },
      {
        id: 'aws-aws-step-functions',
        label: 'AWS Step Functions',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","step","functions"],
      },
      {
        id: 'aws-amazon-app-flow',
        label: 'Amazon App Flow',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","app","flow"],
      },
      {
        id: 'aws-amazon-event-bridge',
        label: 'Amazon Event Bridge',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","event","bridge"],
      },
      {
        id: 'aws-amazon-mq',
        label: 'Amazon MQ',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","mq"],
      },
      {
        id: 'aws-amazon-managed-workflowsfor-apache-airflow',
        label: 'Amazon Managed Workflowsfor Apache Airflow',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","managed","workflowsfor","apache","airflow"],
      },
      {
        id: 'aws-amazon-simple-notification-service',
        label: 'Amazon Simple Notification Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","simple","notification","service"],
      },
      {
        id: 'aws-amazon-simple-queue-service',
        label: 'Amazon Simple Queue Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","simple","queue","service"],
      }
    ],
  },
  {
    label: 'Containers',
    source: 'aws',
    icons: [
      {
        id: 'aws-aws-deep-learning-containers',
        label: 'AWS Deep Learning Containers',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","deep","learning","containers"],
      },
      {
        id: 'aws-aws-secrets-manager',
        label: 'AWS Secrets Manager',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","secrets","manager"],
      },
      {
        id: 'aws-amazon-ecs-anywhere',
        label: 'Amazon ECS Anywhere',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","ecs","anywhere"],
      },
      {
        id: 'aws-amazon-eks-anywhere',
        label: 'Amazon EKS Anywhere',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","eks","anywhere"],
      },
      {
        id: 'aws-amazon-eks-cloud',
        label: 'Amazon EKS Cloud',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","eks","cloud"],
      },
      {
        id: 'aws-amazon-eks-distro',
        label: 'Amazon EKS Distro',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","eks","distro"],
      },
      {
        id: 'aws-amazon-elastic-container-registry',
        label: 'Amazon Elastic Container Registry',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","elastic","container","registry"],
      },
      {
        id: 'aws-amazon-elastic-container-service',
        label: 'Amazon Elastic Container Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","elastic","container","service"],
      }
    ],
  },
  {
    label: 'Customer Engagement',
    source: 'aws',
    icons: [
      {
        id: 'aws-aws-service-management-connector',
        label: 'AWS Service Management Connector',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","service","management","connector"],
      },
      {
        id: 'aws-aws-wickr',
        label: 'AWS Wickr',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","wickr"],
      },
      {
        id: 'aws-amazon-chime',
        label: 'Amazon Chime',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","chime"],
      },
      {
        id: 'aws-amazon-chime-sdk',
        label: 'Amazon Chime SDK',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","chime","sdk"],
      },
      {
        id: 'aws-amazon-connect',
        label: 'Amazon Connect',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","connect"],
      },
      {
        id: 'aws-amazon-pinpoint',
        label: 'Amazon Pinpoint',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","pinpoint"],
      },
      {
        id: 'aws-amazon-pinpoint-ap-is',
        label: 'Amazon Pinpoint AP Is',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","pinpoint","ap","is"],
      },
      {
        id: 'aws-amazon-simple-email-service',
        label: 'Amazon Simple Email Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","simple","email","service"],
      }
    ],
  },
  {
    label: 'Migration',
    source: 'aws',
    icons: [
      {
        id: 'aws-aws-application-discovery-service',
        label: 'AWS Application Discovery Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","application","discovery","service"],
      },
      {
        id: 'aws-aws-application-migration-service',
        label: 'AWS Application Migration Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","application","migration","service"],
      },
      {
        id: 'aws-aws-data-sync',
        label: 'AWS Data Sync',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","data","sync"],
      },
      {
        id: 'aws-aws-data-transfer-terminal',
        label: 'AWS Data Transfer Terminal',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","data","transfer","terminal"],
      },
      {
        id: 'aws-aws-migration-evaluator',
        label: 'AWS Migration Evaluator',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","migration","evaluator"],
      },
      {
        id: 'aws-aws-migration-hub',
        label: 'AWS Migration Hub',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","migration","hub"],
      },
      {
        id: 'aws-aws-transfer-family',
        label: 'AWS Transfer Family',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","transfer","family"],
      }
    ],
  },
  {
    label: 'Front-End & Mobile',
    source: 'aws',
    icons: [
      {
        id: 'aws-aws-amplify',
        label: 'AWS Amplify',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","amplify"],
      },
      {
        id: 'aws-aws-app-sync',
        label: 'AWS App Sync',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","app","sync"],
      },
      {
        id: 'aws-aws-console-mobile-application',
        label: 'AWS Console Mobile Application',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","console","mobile","application"],
      },
      {
        id: 'aws-aws-device-farm',
        label: 'AWS Device Farm',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","device","farm"],
      },
      {
        id: 'aws-amazon-location-service',
        label: 'Amazon Location Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","location","service"],
      }
    ],
  },
  {
    label: 'End User Computing',
    source: 'aws',
    icons: [
      {
        id: 'aws-amazon-app-stream2',
        label: 'Amazon App Stream 2',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","app","stream"],
      },
      {
        id: 'aws-amazon-work-docs',
        label: 'Amazon Work Docs',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","work","docs"],
      },
      {
        id: 'aws-amazon-work-docs-sdk',
        label: 'Amazon Work Docs SDK',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","work","docs","sdk"],
      },
      {
        id: 'aws-amazon-work-mail',
        label: 'Amazon Work Mail',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","work","mail"],
      },
      {
        id: 'aws-amazon-work-spaces-family',
        label: 'Amazon Work Spaces Family',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","work","spaces","family"],
      }
    ],
  },
  {
    label: 'Game',
    source: 'aws',
    icons: [
      {
        id: 'aws-amazon-game-lift-servers',
        label: 'Amazon Game Lift Servers',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","game","lift","servers"],
      },
      {
        id: 'aws-amazon-game-lift-streams',
        label: 'Amazon Game Lift Streams',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","game","lift","streams"],
      }
    ],
  },
  {
    label: 'Satellite',
    source: 'aws',
    icons: [
      {
        id: 'aws-aws-ground-station',
        label: 'AWS Ground Station',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","ground","station"],
      }
    ],
  },
  {
    label: 'Quantum',
    source: 'aws',
    icons: [
      {
        id: 'aws-amazon-braket',
        label: 'Amazon Braket',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","braket"],
      }
    ],
  },
  {
    label: 'Blockchain',
    source: 'aws',
    icons: [
      {
        id: 'aws-amazon-managed-blockchain',
        label: 'Amazon Managed Blockchain',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","managed","blockchain"],
      }
    ],
  },
  {
    label: 'Architecture Groups',
    source: 'aws',
    icons: [
      {
        id: 'aws-group-aws-account',
        label: 'AWS Account',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","account"],
      },
      {
        id: 'aws-group-aws-cloud',
        label: 'AWS Cloud',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","cloud"],
      },
      {
        id: 'aws-group-aws-cloudlogo',
        label: 'AWS Cloudlogo',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","cloudlogo"],
      },
      {
        id: 'aws-group-aws-io-t-greengrass-deployment',
        label: 'AWS Io T Greengrass Deployment',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","io","greengrass","deployment"],
      },
      {
        id: 'aws-group-auto-scalinggroup',
        label: 'Auto Scalinggroup',
        color: '#FF9900',
        source: 'aws',
        tags: ["auto","scalinggroup"],
      },
      {
        id: 'aws-group-corporatedatacenter',
        label: 'Corporatedatacenter',
        color: '#FF9900',
        source: 'aws',
        tags: ["corporatedatacenter"],
      },
      {
        id: 'aws-group-ec2instancecontents',
        label: 'EC 2 instancecontents',
        color: '#FF9900',
        source: 'aws',
        tags: ["ec","instancecontents"],
      },
      {
        id: 'aws-group-privatesubnet',
        label: 'Privatesubnet',
        color: '#FF9900',
        source: 'aws',
        tags: ["privatesubnet"],
      },
      {
        id: 'aws-group-publicsubnet',
        label: 'Publicsubnet',
        color: '#FF9900',
        source: 'aws',
        tags: ["publicsubnet"],
      },
      {
        id: 'aws-group-region',
        label: 'Region',
        color: '#FF9900',
        source: 'aws',
        tags: ["region"],
      },
      {
        id: 'aws-group-servercontents',
        label: 'Servercontents',
        color: '#FF9900',
        source: 'aws',
        tags: ["servercontents"],
      },
      {
        id: 'aws-group-spot-fleet',
        label: 'Spot Fleet',
        color: '#FF9900',
        source: 'aws',
        tags: ["spot","fleet"],
      },
      {
        id: 'aws-group-virtualprivatecloud-vpc',
        label: 'Virtualprivatecloud VPC',
        color: '#FF9900',
        source: 'aws',
        tags: ["virtualprivatecloud","vpc"],
      }
    ],
  },
  {
    label: 'Other Services',
    source: 'aws',
    icons: [
      {
        id: 'aws-aws-activate',
        label: 'AWS Activate',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","activate"],
      },
      {
        id: 'aws-aws-app-fabric',
        label: 'AWS App Fabric',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","app","fabric"],
      },
      {
        id: 'aws-aws-app-studio',
        label: 'AWS App Studio',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","app","studio"],
      },
      {
        id: 'aws-aws-application-auto-scaling',
        label: 'AWS Application Auto Scaling',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","application","auto","scaling"],
      },
      {
        id: 'aws-aws-audit-manager',
        label: 'AWS Audit Manager',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","audit","manager"],
      },
      {
        id: 'aws-aws-auto-scaling',
        label: 'AWS Auto Scaling',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","auto","scaling"],
      },
      {
        id: 'aws-aws-backint-agent',
        label: 'AWS Backint Agent',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","backint","agent"],
      },
      {
        id: 'aws-aws-cloud-control-api',
        label: 'AWS Cloud Control API',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","cloud","control","api"],
      },
      {
        id: 'aws-aws-cloud-development-kit',
        label: 'AWS Cloud Development Kit',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","cloud","development","kit"],
      },
      {
        id: 'aws-aws-costand-usage-report',
        label: 'AWS Costand Usage Report',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","costand","usage","report"],
      },
      {
        id: 'aws-aws-deep-learning-am-is',
        label: 'AWS Deep Learning AM Is',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","deep","learning","am","is"],
      },
      {
        id: 'aws-aws-distrofor-open-telemetry',
        label: 'AWS Distrofor Open Telemetry',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","distrofor","open","telemetry"],
      },
      {
        id: 'aws-aws-end-user-messaging',
        label: 'AWS End User Messaging',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","end","user","messaging"],
      },
      {
        id: 'aws-aws-health-imaging',
        label: 'AWS Health Imaging',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","health","imaging"],
      },
      {
        id: 'aws-aws-health-scribe',
        label: 'AWS Health Scribe',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","health","scribe"],
      },
      {
        id: 'aws-awsiq',
        label: 'AWSIQ',
        color: '#FF9900',
        source: 'aws',
        tags: ["awsiq"],
      },
      {
        id: 'aws-aws-infrastructure-composer',
        label: 'AWS Infrastructure Composer',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","infrastructure","composer"],
      },
      {
        id: 'aws-aws-key-management-service',
        label: 'AWS Key Management Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","key","management","service"],
      },
      {
        id: 'aws-aws-local-zones',
        label: 'AWS Local Zones',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","local","zones"],
      },
      {
        id: 'aws-aws-managed-services',
        label: 'AWS Managed Services',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","managed","services"],
      },
      {
        id: 'aws-aws-management-console',
        label: 'AWS Management Console',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","management","console"],
      },
      {
        id: 'aws-aws-marketplace',
        label: 'AWS Marketplace',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","marketplace"],
      },
      {
        id: 'aws-aws-private5g',
        label: 'AWS Private 5 G',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","private"],
      },
      {
        id: 'aws-aws-professional-services',
        label: 'AWS Professional Services',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","professional","services"],
      },
      {
        id: 'aws-aws-sim-space-weaver',
        label: 'AWS Sim Space Weaver',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","sim","space","weaver"],
      },
      {
        id: 'aws-aws-supply-chain',
        label: 'AWS Supply Chain',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","supply","chain"],
      },
      {
        id: 'aws-aws-support',
        label: 'AWS Support',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","support"],
      },
      {
        id: 'aws-aws-toolsand-sd-ks',
        label: 'AWS Toolsand SD Ks',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","toolsand","sd","ks"],
      },
      {
        id: 'aws-aws-training-certification',
        label: 'AWS Training Certification',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","training","certification"],
      },
      {
        id: 'aws-aws-transform',
        label: 'AWS Transform',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","transform"],
      },
      {
        id: 'aws-aws-user-notifications',
        label: 'AWS User Notifications',
        color: '#FF9900',
        source: 'aws',
        tags: ["aws","user","notifications"],
      },
      {
        id: 'aws-aw-sre-post',
        label: 'AW Sre Post',
        color: '#FF9900',
        source: 'aws',
        tags: ["aw","sre","post"],
      },
      {
        id: 'aws-aw-sre-post-private',
        label: 'AW Sre Post Private',
        color: '#FF9900',
        source: 'aws',
        tags: ["aw","sre","post","private"],
      },
      {
        id: 'aws-amazon-application-recovery-controller',
        label: 'Amazon Application Recovery Controller',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","application","recovery","controller"],
      },
      {
        id: 'aws-amazon-cloud-search',
        label: 'Amazon Cloud Search',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","cloud","search"],
      },
      {
        id: 'aws-amazon-dcv',
        label: 'Amazon DCV',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","dcv"],
      },
      {
        id: 'aws-amazon-data-firehose',
        label: 'Amazon Data Firehose',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","data","firehose"],
      },
      {
        id: 'aws-amazon-dev-ops-guru',
        label: 'Amazon Dev Ops Guru',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","dev","ops","guru"],
      },
      {
        id: 'aws-amazon-elastic-inference',
        label: 'Amazon Elastic Inference',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","elastic","inference"],
      },
      {
        id: 'aws-amazon-elastic-kubernetes-service',
        label: 'Amazon Elastic Kubernetes Service',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","elastic","kubernetes","service"],
      },
      {
        id: 'aws-amazon-managed-servicefor-apache-flink',
        label: 'Amazon Managed Servicefor Apache Flink',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","managed","servicefor","apache","flink"],
      },
      {
        id: 'aws-amazon-managed-servicefor-prometheus',
        label: 'Amazon Managed Servicefor Prometheus',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","managed","servicefor","prometheus"],
      },
      {
        id: 'aws-amazon-nova',
        label: 'Amazon Nova',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","nova"],
      },
      {
        id: 'aws-amazon-q',
        label: 'Amazon Q',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon"],
      },
      {
        id: 'aws-amazon-verified-permissions',
        label: 'Amazon Verified Permissions',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","verified","permissions"],
      },
      {
        id: 'aws-amazon-virtual-private-cloud',
        label: 'Amazon Virtual Private Cloud',
        color: '#FF9900',
        source: 'aws',
        tags: ["amazon","virtual","private","cloud"],
      },
      {
        id: 'aws-apache-mx-neton-aws',
        label: 'Apache MX Neton AWS',
        color: '#FF9900',
        source: 'aws',
        tags: ["apache","mx","neton","aws"],
      },
      {
        id: 'aws-elastic-fabric-adapter',
        label: 'Elastic Fabric Adapter',
        color: '#FF9900',
        source: 'aws',
        tags: ["elastic","fabric","adapter"],
      },
      {
        id: 'aws-free-rtos',
        label: 'Free RTOS',
        color: '#FF9900',
        source: 'aws',
        tags: ["free","rtos"],
      },
      {
        id: 'aws-open3d-engine',
        label: 'Open 3 D Engine',
        color: '#FF9900',
        source: 'aws',
        tags: ["open","engine"],
      },
      {
        id: 'aws-py-torchon-aws',
        label: 'Py Torchon AWS',
        color: '#FF9900',
        source: 'aws',
        tags: ["py","torchon","aws"],
      },
      {
        id: 'aws-red-hat-open-shift-serviceon-aws',
        label: 'Red Hat Open Shift Serviceon AWS',
        color: '#FF9900',
        source: 'aws',
        tags: ["red","hat","open","shift","serviceon","aws"],
      },
      {
        id: 'aws-reserved-instance-reporting',
        label: 'Reserved Instance Reporting',
        color: '#FF9900',
        source: 'aws',
        tags: ["reserved","instance","reporting"],
      },
      {
        id: 'aws-savings-plans',
        label: 'Savings Plans',
        color: '#FF9900',
        source: 'aws',
        tags: ["savings","plans"],
      },
      {
        id: 'aws-tensor-flowon-aws',
        label: 'Tensor Flowon AWS',
        color: '#FF9900',
        source: 'aws',
        tags: ["tensor","flowon","aws"],
      }
    ],
  }
];

export const awsCategories: Record<string, IconCategory> = Object.fromEntries(
  awsCategoriesArray.map((cat) => [cat.label, cat])
);

export const getAllAwsIcons = () => {
  return awsCategoriesArray.flatMap((cat) => cat.icons);
};

export default awsCategoriesArray;
