export { AwsIcon, AzureIcon, GcpIcon, KubernetesIcon, DockerIcon, DigitalOceanIcon, OracleCloudIcon, } from './cloud-providers';
export { ServerIcon, VirtualMachineIcon, ContainerIcon, LambdaIcon, } from './infrastructure';
export { DatabaseIcon, RedisIcon, MongoDbIcon, PostgresIcon, MySqlIcon, } from './database';
export { NetworkIcon, RouterIcon, SwitchIcon, FirewallIcon, LoadBalancerIcon, VpnIcon, DnsIcon, CdnIcon, } from './networking';
export { internalCategories } from './categories';
export declare const internalIconMap: {
    aws: any;
    azure: any;
    gcp: any;
    kubernetes: any;
    docker: any;
    digitalocean: any;
    oracle: any;
    server: any;
    vm: any;
    container: any;
    lambda: any;
    database: any;
    redis: any;
    mongodb: any;
    postgres: any;
    mysql: any;
    network: any;
    router: any;
    switch: any;
    firewall: any;
    loadbalancer: any;
    vpn: any;
    dns: any;
    cdn: any;
};
