apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: icecharts

commonLabels:
  app.kubernetes.io/name: icecharts
  app.kubernetes.io/managed-by: kustomize

resources:
  - configmap.yaml
  - web-deployment.yaml
  - web-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - redis-statefulset.yaml
  - redis-service.yaml
  - minio-statefulset.yaml
  - minio-service.yaml
