apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "icecharts.fullname" . }}-config
  namespace: {{ include "icecharts.namespace" . }}
  labels:
    {{- include "icecharts.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  DB_HOST: {{ include "icecharts.dbHost" . | quote }}
  REDIS_HOST: {{ include "icecharts.redisHost" . | quote }}
  MINIO_ENDPOINT: {{ include "icecharts.minioEndpoint" . | quote }}
