{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ include "icecharts.namespace" . }}
  labels:
    {{- include "icecharts.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "icecharts.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
  ports:
  - port: {{ .Values.minio.ports.api }}
    targetPort: {{ .Values.minio.ports.api }}
    protocol: TCP
    name: api
  - port: {{ .Values.minio.ports.console }}
    targetPort: {{ .Values.minio.ports.console }}
    protocol: TCP
    name: console
{{- end }}
