{{- if .Values.minio.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "icecharts.fullname" . }}-minio
  namespace: {{ include "icecharts.namespace" . }}
  labels:
    {{- include "icecharts.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      {{- include "icecharts.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        {{- include "icecharts.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: minio
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
      containers:
      - name: minio
        image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
        command: ["minio", "server", "/data", "--console-address", ":9001"]
        ports:
        - containerPort: {{ .Values.minio.ports.api }}
          protocol: TCP
          name: api
        - containerPort: {{ .Values.minio.ports.console }}
          protocol: TCP
          name: console
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "icecharts.fullname" . }}-secret
              key: MINIO_ACCESS_KEY
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "icecharts.fullname" . }}-secret
              key: MINIO_SECRET_KEY
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        resources:
          {{- toYaml .Values.minio.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: {{ .Values.minio.ports.api }}
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: {{ .Values.minio.ports.api }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: minio-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: minio-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.minio.storage }}
{{- end }}
