apiVersion: v1
kind: ConfigMap
metadata:
  name: icecharts-config
data:
  FLASK_ENV: "development"
  LOG_LEVEL: "debug"
  RELEASE_MODE: "false"
  CORS_ORIGINS: "http://localhost:3000"
  DB_HOST: "postgres.icecharts-dev.svc.cluster.local"
  REDIS_HOST: "redis.icecharts-dev.svc.cluster.local"
  MINIO_ENDPOINT: "minio.icecharts-dev.svc.cluster.local:9000"
