apiVersion: v1
kind: ConfigMap
metadata:
  name: icecharts-config
data:
  FLASK_ENV: "production"
  LOG_LEVEL: "warning"
  RELEASE_MODE: "true"
  CORS_ORIGINS: "https://icecharts.penguincloud.io"
  DB_HOST: "postgres.icecharts-prod.svc.cluster.local"
  REDIS_HOST: "redis.icecharts-prod.svc.cluster.local"
  MINIO_ENDPOINT: "minio.icecharts-prod.svc.cluster.local:9000"
